### ISSUE TITLE
Uncaught Reference/TypeError

### ISSUE THREAD

**Issue by KittiKitti** [awaken1ng/bd-linestickers#8]
Hi there -
I'm just starting to delve into adding plugins and themes, so I may just be misunderstanding a step, but when I go to execute the _lineemotes.appendPack(`title`, first_sticker_id, length)_ command in the console, I get an "Uncaught ReferenceError" error. When I execute the command with the sticker pack's title, first sticker ID, and append string, I get an "Uncaught TypeError" error.
Is there something I am missing?

Thank so much for the help - excited to get this working!

**Comment by awaken1ng** [comment]
Assuming the ReferenceError looked like this
![](https://camo.githubusercontent.com/adb46a88d271721467e3c569950cfddd89a69d01/68747470733a2f2f63646e2e646973636f72646170702e636f6d2f6174746163686d656e74732f3330363032303830333534363434373837322f3331323734323134323634323438373331302f756e6b6e6f776e2e706e67)
as you might have already guessed, you're passing empty variables to the function

Not sure about the TypeError, but it might have been because I didn't put a proper type check on first sticker ID, if you can provide the full command you've used I might have a better guess at what went wrong. I've updated the plugin a little to include the said check

The append string (the command that you execute in the console) should look like this ``lineemotes.appendPack(`Miko sister of fox`, 1133826, 40)``, the title as a string and two integers, the first sticker ID and optionally length, if its not explicitly set it will default to 40

**Comment by KittiKitti** [comment]
It seems like your inkling may have been right - the updated plugin now works for me. Not sure if this is where things went wrong, but , regardless, all is well now!
Thanks so much for the update and explanation!
